module.exports={
    modeList:{
        "ball-scale-ripple":{count:1,css:{bgcolor:"#000"}},
        "line-spin-fade-loader":{count:8,css:{bgcolor:"#000"}},
        "ball-spin-fade-loader":{count:8,color:"#fff"},
        "pacman":{count:5,color:"#fff"},
        "ball-clip-rotate":{count:1,color:"#fff"}
    }
}